# Generated by Django 5.0.6 on 2024-07-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_first_app", "0004_publisher_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="Publisher",
            new_name="publisher",
        ),
    ]
